### ISSUE TITLE
But python is so much cleaner now, why don't u use that? :)

### ISSUE THREAD

**Issue by sorl** [jesperp/koa-react-bootstrap#1]
https://github.com/KeepSafe/aiohttp/
https://www.python.org/dev/peps/pep-0492/

**Comment by jesperp** [comment]
Oh, python 3.5 looks pretty awesome! Finally an `async` keyword too :relieved:
thanks for the heads up :+1:

**Comment by jesperp** [comment]
closing as wontfix tho' :wink:
